//
//  Configuration.h
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#ifndef DigitalNewzealandRR_Configuration_h
#define DigitalNewzealandRR_Configuration_h

@interface Configuration : NSObject

/** The base Uri for API calls */
+(NSString*) BaseUri;

/** Your API Key */
+(NSString*) ApiKey;


@end

#endif
