//
//  Configuration.m
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#import "Configuration.h"

@implementation Configuration

/** The base Uri for API calls */
+(NSString*) BaseUri
{
    return @"http://api.digitalnz.org";
}

/** Your API Key */
+(NSString*) ApiKey
{
    return [[NSBundle mainBundle] objectForInfoDictionaryKey:@"ApiKey"];
}


@end