//
//  MetadataController.h
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CollectionSearchRecords.h"
#import "GetMetadataInput.h"

@interface MetadataController : BaseController

/**
* Completion block definition for asynchronous call to Get Metadata */
typedef void (^CompletedGetMetadata)(BOOL success, HttpContext* context, CollectionSearchRecords* response, NSError* error);

/**
* The Get Metadata API call returns the available metadata for a specific item. The Get Metadata v3 request parameters and response format differs significantly from the depreciated Get Metadata v1 & v2 API call.
* @param  GetMetadataInput     Object with all parameters
*/
- (void) getMetadataAsyncWithGetMetadataInput:(GetMetadataInput*) input
                completionBlock:(CompletedGetMetadata) onCompleted;

@end