//
//  SearchRecordController.h
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CollectionSearchRecords.h"
#import "SearchRecordInput.h"

@interface SearchRecordController : BaseController

/**
* Completion block definition for asynchronous call to SearchRecord */
typedef void (^CompletedGetSearchRecord)(BOOL success, HttpContext* context, CollectionSearchRecords* response, NSError* error);

/**
* The Search Records API call returns a result set in response to a search query. The v3 Search Records API request parameters and response format differs significantly from the deprecated v1 & v2 Search Records API call.
* @param  SearchRecordInput     Object with all parameters
*/
- (void) searchRecordAsyncWithSearchRecordInput:(SearchRecordInput*) input
                completionBlock:(CompletedGetSearchRecord) onCompleted;

@end