//
//  CollectionSearchRecords.h
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#ifndef APIMATIC_COLLECTIONSEARCHRECORDS
#define APIMATIC_COLLECTIONSEARCHRECORDS

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ResultsCollection.h"


//protocol defined for deserialization of JSON
@protocol CollectionSearchRecords
@end

@interface CollectionSearchRecords : JSONModel

/**
* the facet result data (if requested). The facets element will contain one facet-field element corresponding to each facet requested. Each facet-field element contains a sorted list of value elements that are made up of a name and num-results element. 
*/
@property NSDictionary* facets;

/**
* the value of the num_results parameter sent to the API method
*/
@property int numResultsRequested;

/**
* the total number of results matching this search
*/
@property int resultCount;

/**
* the search results data. The results element will contain 0 or more result elements
*/
@property ResultsCollection* results;

/**
* the value of the start parameter sent to the API method
*/
@property NSString* start;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif