//
//  GetMetadataInput.m
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#import "GetMetadataInput.h"

@implementation GetMetadataInput

/**
* Record IDs are identified in the metadata_url field of a results set. 23034653 is an example record ID.
*/
@synthesize recordId;

/**
* A comma separated list of fields or groups of fields to be returned for each record. Possible groups include 'default' and 'verbose'. If no value is specified, then the 'default' field group will be returned.
*/
@synthesize fields;

@end