//
//  GetMetadataInput.h
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#ifndef APIMATIC_GETMETADATAINPUT
#define APIMATIC_GETMETADATAINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol GetMetadataInput
@end

@interface GetMetadataInput : NSObject

/**
* Record IDs are identified in the metadata_url field of a results set. 23034653 is an example record ID.
*/
@property NSString* recordId;

/**
* A comma separated list of fields or groups of fields to be returned for each record. Possible groups include 'default' and 'verbose'. If no value is specified, then the 'default' field group will be returned.
*/
@property NSString* fields;

@end
#endif