//
//  SearchRecordInput.h
//  DigitalNewzealandRR
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
//
#ifndef APIMATIC_SEARCHRECORDINPUT
#define APIMATIC_SEARCHRECORDINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol SearchRecordInput
@end

@interface SearchRecordInput : NSObject

/**
* TODO: Write general description for this field
*/
@property NSString* text;

/**
* Restricts search to records matching all facet values. Example: "&and[content_partner][]=Kete+Horowhenua&and[category][]=Images"
*/
@property NSString* and;

/**
* Restricts search to records matching any of the specified facet values. Example: "&or[category][]=Image&or[category][]=Videos"without 
*/
@property NSString* or;

/**
* Restricts search to records that don't match any of the facet values. Example: "&without[category][]=Newspapers"
*/
@property NSString* without;

/**
* the page when iterating over a set of records. (Defaults to 1.)
*/
@property int page;

/**
* the number of records the user wishes returned up to a maximum of 100. (Defaults to 20.)
*/
@property int perPage;

/**
* a list of facet fields to include in the output. See the note on facets below for more information. Example: "&facets=year,category"
*/
@property NSString* facets;

/**
* the facet page to iterate over a set of facets. . (Defaults to 1.)
*/
@property int facetsPage;

/**
* the number of facets returned for every page. (Defaults to 10.)
*/
@property int facetPerPage;

/**
* the field upon which results are sorted. Defaults to relevance sorting. The sort field must be one of: "category", "content_partner", "date", "syndication_date".
*/
@property NSString* sort;

/**
*  the direction in which the results are sorted. Possible values: "desc", "asc".
*/
@property NSString* direction;

/**
* a geographic bounding box scoping a search to a geographic region. Order of latitude-longitude coordinates is north, west, south, east. For example, &geo_bbox=-41,174,-42,175 searches the Wellington region.
*/
@property NSNumber* geoBbox;

@end
#endif